from abc import ABC, abstractmethod
from model.abstract_timer import ATimer
from model.abstract_event_publisher import EventPublisher
from model.observable import Observable
from model.schedule import Schedule
from datetime import datetime

class Model(EventPublisher, ABC):
    """
    Abstract class for the model.
    """
    def __init__(self) -> None:
        pass

    @abstractmethod
    def mainloop(self) -> None:
        pass

    @abstractmethod
    def get_schedule(self) -> Schedule:
        """Returns a schedule generated by a chosen mimicking algorithm

        Returns:
            Schedule: The algorithm based schedule
        """
        pass
    
    @abstractmethod
    def get_user_schedule(self) -> Schedule:
        """Returns a schedule based on pure user data, without modification due to an algorithm.

        Returns:
            Schedule: A schedule based on pure user data
        """
        pass
    
    @abstractmethod
    def toggle_generated_schedule(self):
        """Used to toggle between the schedule created by the pure user data and the algorithm based schedule.
        """
        pass
    
    @abstractmethod
    def get_current_schedule(self) -> Schedule:
        """ Returns the current schedule being used by the model.

        Returns:
            Schedule: the current schedule being used by the model
        """
        pass

    @abstractmethod
    def get_time(self) -> datetime:
        pass

    @abstractmethod
    def set_time(self, time: datetime) -> None:
        pass

    @abstractmethod
    def start(self) -> None:
        pass

    @abstractmethod
    def stop(self) -> None:
        pass

    @abstractmethod
    def add_observer(self, observer) -> None:
        pass

    @abstractmethod
    def remove_observer(self, observer) -> None:
        pass